services:
  - type: web
    name: my-django-app
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn MyBlog.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: MyBlog.settings
      - key: SECRET_KEY
        generateValue: true
